alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'slack-notifications'
      routes:
        - matchers:
            - severity="critical"
          receiver: 'slack-notifications'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - send_resolved: true
            channel: '#guillermo-prometheus-alarms'   # Canal real
            username: 'PrometheusBot'
            icon_emoji: ':rotating_light:'
            api_url: 'https://hooks.slack.com/services/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'
            title: "*[{{ .Status | toUpper }}]* {{ .CommonLabels.alertname }}"
            text: >
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Severity:* {{ .Labels.severity }}
              *Starts At:* {{ .StartsAt }}
              *Ends At:* {{ .EndsAt }}
              {{ end }}
