name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USER }}/mi-fastapi-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USER }}/mi-fastapi-app:${{ github.sha }}
          docker push $IMAGE_NAME

      - name: Replace Slack webhook in Alertmanager config
        run: |
          sed -i "s|https://hooks.slack.com/services/PLACEHOLDER|${{ secrets.SLACK_WEBHOOK_URL }}|" helm-values/alertmanager.yaml

      - name: Upgrade kube-prometheus-stack with Helm
        run: |
          helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            -f helm-values/alertmanager.yaml \
            -f helm-values/additional-rules.yaml \
            --install
