name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          # Se utiliza el hash del commit para etiquetar la imagen
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USER }}/mi-fastapi-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USER }}/mi-fastapi-app:${{ github.sha }}
          docker push $IMAGE_NAME
